### ISSUE TITLE
Still work ?

### ISSUE THREAD

**Issue by aguidis** [khrome/xbox-live#2]
Hi,

I'll need a way to authenticate a user thanks to his gamer tag. I would like to know if your module still work ? (any API update needed ?)

Thanks

**Comment by yllanos** [comment]
I'm also interested

**Comment by khrome** [comment]
There is no way to authenticate against an xbox account, however depending on your use case it could be possible to link a user/session to an XBL account. I have not tried it lately, but it does have a test suite, try starting there. Be forewarned, the endpoints which expose this kind of data have always been flaky and unreliable(fails one second, claims invalid account, or returns data randomly) and you'll have to code around this behaviour.

**Comment by BasixKOR** [comment]
+1

**Comment by khrome** [comment]
Now working without any APIs required, API support is coming.
